# 基于EEG的吸烟成瘾评估系统 - 主配置文件
# 此文件定义了整个项目的默认配置，通过Hydra进行管理

# 默认配置组合 - 指定要加载的配置文件
defaults:
  - data: default              # 数据配置
  - preprocessing: default     # 预处理配置
  - features: default          # 特征提取配置
  - models: default            # 模型配置
  - _self_                     # 当前配置

# 全局设置
global:
  # 输出目录设置
  output_dir: "outputs"        # 主输出目录
  results_dir: "outputs/results"  # 结果存储目录
  models_dir: "outputs/models"    # 模型存储目录
  reports_dir: "outputs/reports"  # 报告存储目录
  figures_dir: "outputs/figures"  # 图像存储目录
  
  # 日志设置
  log_level: "INFO"            # 日志级别：DEBUG, INFO, WARNING, ERROR
  log_file: "outputs/logs/experiment.log"  # 日志文件路径
  
  # 实验设置
  random_seed: 42              # 随机种子，确保结果可重现
  n_jobs: -1                   # 并行处理作业数，-1表示使用所有CPU核心
  
  # 数据设置
  save_intermediate: true      # 是否保存中间结果
  overwrite: false             # 是否覆盖已存在的结果文件

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

# Global settings
data_dir: "data"
output_dir: "outputs"
log_level: "INFO"

# Experiment settings
experiment_name: "smoke_addiction_assessment"
random_seed: 42
n_jobs: -1

